export const perfis = [
  'Diretor',
  'Magistrado',
  'Assessor',
  'Servidor',
  'Advogado',
  'Perito',
  'Procurador',
  'Outros'
];

export const graus = [
  '1º Grau',
  '2º Grau'
];

export const orgaosJulgadores = [
  { codigo: '1', nome: '1ª Vara do Trabalho de Campinas' },
  { codigo: '2', nome: '1ª Vara do Trabalho de Jundiaí' },
  { codigo: '3', nome: '1ª Vara do Trabalho de Sorocaba' },
  { codigo: '4', nome: '1ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '5', nome: '1ª Vara do Trabalho de Bauru' },
  { codigo: '6', nome: '1ª Vara do Trabalho de Araraquara' },
  { codigo: '7', nome: '1ª Vara do Trabalho de Americana' },
  { codigo: '8', nome: '1ª Vara do Trabalho de São Carlos' },
  { codigo: '9', nome: '1ª Vara do Trabalho de Taubaté' },
  { codigo: '10', nome: 'Vara do Trabalho de Rio Claro' },
  { codigo: '11', nome: 'Vara do Trabalho de Barretos' },
  { codigo: '12', nome: '1ª Vara do Trabalho de Piracicaba' },
  { codigo: '13', nome: '1ª Vara do Trabalho de São José dos Campos' },
  { codigo: '14', nome: '1ª Vara do Trabalho de Limeira' },
  { codigo: '15', nome: '1ª Vara do Trabalho de Franca' },
  { codigo: '16', nome: '2ª Vara do Trabalho de Sorocaba' },
  { codigo: '17', nome: '1ª Vara do Trabalho de São José do Rio Preto' },
  { codigo: '18', nome: 'Vara do Trabalho de Itu' },
  { codigo: '19', nome: '1ª Vara do Trabalho de Araçatuba' },
  { codigo: '20', nome: 'Vara do Trabalho de Guaratinguetá' },
  { codigo: '21', nome: '2ª Vara do Trabalho de Jundiaí' },
  { codigo: '22', nome: 'Vara do Trabalho de Mogi Mirim' },
  { codigo: '23', nome: '1ª Vara do Trabalho de Jacareí' },
  { codigo: '24', nome: '1ª Vara do Trabalho de Jaú' },
  { codigo: '25', nome: 'Vara do Trabalho de Botucatu' },
  { codigo: '26', nome: '1ª Vara do Trabalho de Presidente Prudente' },
  { codigo: '27', nome: 'Vara do Trabalho de Votuporanga' },
  { codigo: '28', nome: '1ª Vara do Trabalho de Catanduva' },
  { codigo: '29', nome: '1ª Vara do Trabalho de Jaboticabal' },
  { codigo: '30', nome: 'Vara do Trabalho de Ourinhos' },
  { codigo: '31', nome: 'Vara do Trabalho de Avaré' },
  { codigo: '32', nome: '2ª Vara do Trabalho de Campinas' },
  { codigo: '33', nome: '1ª Vara do Trabalho de Marília' },
  { codigo: '34', nome: 'Vara do Trabalho de São João da Boa Vista' },
  { codigo: '35', nome: 'Vara do Trabalho de São José do Rio Pardo' },
  { codigo: '36', nome: '1ª Vara do Trabalho de Assis' },
  { codigo: '37', nome: 'Vara do Trabalho de Fernandópolis' },
  { codigo: '38', nome: 'Vara do Trabalho de Bragança Paulista' },
  { codigo: '39', nome: 'Vara do Trabalho de Capivari' },
  { codigo: '40', nome: 'Vara do Trabalho de Cruzeiro' },
  { codigo: '41', nome: 'Vara do Trabalho de Itapetininga' },
  { codigo: '42', nome: '2ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '43', nome: '3ª Vara do Trabalho de Campinas' },
  { codigo: '44', nome: '2ª Vara do Trabalho de São José do Rio Preto' },
  { codigo: '45', nome: '2ª Vara do Trabalho de São José dos Campos' },
  { codigo: '46', nome: 'Vara do Trabalho de Araras' },
  { codigo: '47', nome: 'Vara do Trabalho de Itapeva' },
  { codigo: '48', nome: 'Vara do Trabalho de Porto Ferreira' },
  { codigo: '49', nome: 'Vara do Trabalho de Itápolis' },
  { codigo: '50', nome: 'Vara do Trabalho de Dracena' },
  { codigo: '51', nome: '2ª Vara do Trabalho de Piracicaba' },
  { codigo: '52', nome: 'Vara do Trabalho de Ituverava' },
  { codigo: '53', nome: '4ª Vara do Trabalho de Campinas' },
  { codigo: '54', nome: '1ª Vara do Trabalho de Sertãozinho' },
  { codigo: '55', nome: '2ª Vara do Trabalho de Jaú' },
  { codigo: '56', nome: 'Vara do Trabalho de Andradina' },
  { codigo: '57', nome: 'Vara do Trabalho de Presidente Venceslau' },
  { codigo: '58', nome: 'Vara do Trabalho de Bebedouro' },
  { codigo: '59', nome: 'Vara do Trabalho de Pindamonhangaba' },
  { codigo: '60', nome: 'Vara do Trabalho de Amparo' },
  { codigo: '61', nome: '2ª Vara do Trabalho de Araçatuba' },
  { codigo: '62', nome: 'Vara do Trabalho de Lins' },
  { codigo: '63', nome: 'Vara do Trabalho de Caraguatatuba' },
  { codigo: '64', nome: 'Vara do Trabalho de Itanhaém' },
  { codigo: '65', nome: 'Vara do Trabalho de Tupã' },
  { codigo: '66', nome: '3ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '67', nome: '4ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '68', nome: 'Vara do Trabalho de Adamantina' },
  { codigo: '69', nome: 'Vara do Trabalho de Registro' },
  { codigo: '70', nome: '2ª Vara do Trabalho de Catanduva' },
  { codigo: '71', nome: 'Vara do Trabalho de Mogi Guaçu' },
  { codigo: '72', nome: 'Vara do Trabalho de Rancharia' },
  { codigo: '73', nome: 'Vara do Trabalho de Birigui' },
  { codigo: '74', nome: '1ª Vara do Trabalho de Lençóis Paulista' },
  { codigo: '75', nome: 'Vara do Trabalho de Batatais' },
  { codigo: '76', nome: '2ª Vara do Trabalho de Franca' },
  { codigo: '77', nome: 'Vara do Trabalho de Indaiatuba' },
  { codigo: '78', nome: 'Vara do Trabalho de Piedade' },
  { codigo: '79', nome: '2ª Vara do Trabalho de Araraquara' },
  { codigo: '80', nome: 'Vara do Trabalho de Jales' },
  { codigo: '81', nome: 'Vara do Trabalho de Matão' },
  { codigo: '82', nome: '3ª Vara do Trabalho de São José do Rio Preto' },
  { codigo: '83', nome: '3ª Vara do Trabalho de São José dos Campos' },
  { codigo: '84', nome: '4ª Vara do Trabalho de São José dos Campos' },
  { codigo: '85', nome: 'Vara do Trabalho de Salto' },
  { codigo: '86', nome: 'Vara do Trabalho de Santa Bárbara D\'Oeste' },
  { codigo: '87', nome: '1ª Vara do Trabalho de Paulínia' },
  { codigo: '88', nome: 'Vara do Trabalho de Lorena' },
  { codigo: '89', nome: '2ª Vara do Trabalho de Bauru' },
  { codigo: '90', nome: '3ª Vara do Trabalho de Bauru' },
  { codigo: '91', nome: '4ª Vara do Trabalho de Bauru' },
  { codigo: '92', nome: '5ª Vara do Trabalho de Campinas' },
  { codigo: '93', nome: '6ª Vara do Trabalho de Campinas' },
  { codigo: '94', nome: '7ª Vara do Trabalho de Campinas' },
  { codigo: '95', nome: '8ª Vara do Trabalho de Campinas' },
  { codigo: '96', nome: '3ª Vara do Trabalho de Jundiaí' },
  { codigo: '97', nome: '4ª Vara do Trabalho de Jundiaí' },
  { codigo: '98', nome: 'Vara do Trabalho de Garça' },
  { codigo: '99', nome: '2ª Vara do Trabalho de Americana' },
  { codigo: '100', nome: '2ª Vara do Trabalho de Assis' },
  { codigo: '101', nome: '2ª Vara do Trabalho de Marília' },
  { codigo: '102', nome: '2ª Vara do Trabalho de Taubaté' },
  { codigo: '103', nome: '3ª Vara do Trabalho de Araçatuba' },
  { codigo: '104', nome: 'Vara do Trabalho de Tanabi' },
  { codigo: '105', nome: 'Vara do Trabalho de Campo Limpo Paulista' },
  { codigo: '106', nome: '2ª Vara do Trabalho de São Carlos' },
  { codigo: '107', nome: 'Vara do Trabalho de Olímpia' },
  { codigo: '108', nome: 'Vara do Trabalho de São Roque' },
  { codigo: '109', nome: '3ª Vara do Trabalho de Sorocaba' },
  { codigo: '110', nome: 'Vara do Trabalho de José Bonifácio' },
  { codigo: '111', nome: 'Vara do Trabalho de Tietê' },
  { codigo: '112', nome: 'Vara do Trabalho de Cajuru' },
  { codigo: '113', nome: '5ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '114', nome: '9ª Vara do Trabalho de Campinas' },
  { codigo: '115', nome: '2ª Vara do Trabalho de Presidente Prudente' },
  { codigo: '116', nome: 'Vara do Trabalho de Tatuí' },
  { codigo: '117', nome: 'Vara do Trabalho de São Joaquim da Barra' },
  { codigo: '118', nome: 'Vara do Trabalho de Itapira' },
  { codigo: '119', nome: 'Vara do Trabalho de Caçapava' },
  { codigo: '120', nome: '2ª Vara do Trabalho de Jaboticabal' },
  { codigo: '121', nome: 'Vara do Trabalho de São Sebastião' },
  { codigo: '122', nome: 'Vara do Trabalho de Sumaré' },
  { codigo: '123', nome: 'Vara do Trabalho de Capão Bonito' },
  { codigo: '124', nome: 'Vara do Trabalho de Penápolis' },
  { codigo: '125', nome: '2ª Vara do Trabalho de Sertãozinho' },
  { codigo: '126', nome: '2ª Vara do Trabalho de Paulínia' },
  { codigo: '127', nome: 'Vara do Trabalho de Teodoro Sampaio' },
  { codigo: '128', nome: '2ª Vara do Trabalho de Limeira' },
  { codigo: '129', nome: '10ª Vara do Trabalho de Campinas' },
  { codigo: '130', nome: '11ª Vara do Trabalho de Campinas' },
  { codigo: '131', nome: '12ª Vara do Trabalho de Campinas' },
  { codigo: '132', nome: '5ª Vara do Trabalho de São José dos Campos' },
  { codigo: '133', nome: '4ª Vara do Trabalho de São José do Rio Preto' },
  { codigo: '134', nome: 'Vara do Trabalho de Leme' },
  { codigo: '135', nome: '4ª Vara do Trabalho de Sorocaba' },
  { codigo: '136', nome: 'Vara do Trabalho de Pirassununga' },
  { codigo: '137', nome: '3ª Vara do Trabalho de Piracicaba' },
  { codigo: '138', nome: '2ª Vara do Trabalho de Jacareí' },
  { codigo: '139', nome: 'Vara do Trabalho de Ubatuba' },
  { codigo: '140', nome: 'Vara do Trabalho de Atibaia' },
  { codigo: '141', nome: 'Vara do Trabalho de Mococa' },
  { codigo: '142', nome: 'Vara do Trabalho de Taquaritinga' },
  { codigo: '143', nome: 'Vara do Trabalho de Santa Cruz do Rio Pardo' },
  { codigo: '144', nome: 'Vara do Trabalho de Pederneiras' },
  { codigo: '145', nome: 'Vara do Trabalho de Itatiba' },
  { codigo: '146', nome: 'Vara do Trabalho de Orlândia' },
  { codigo: '147', nome: 'Vara do Trabalho de Aparecida' },
  { codigo: '148', nome: 'Vara do Trabalho de Itararé' },
  { codigo: '149', nome: '2ª Vara do Trabalho de Lençóis Paulista' },
  { codigo: '150', nome: 'Vara do Trabalho de Cravinhos' },
  { codigo: '151', nome: '3ª Vara do Trabalho de Araraquara' },
  { codigo: '152', nome: 'Vara do Trabalho de Hortolândia' },
  { codigo: '153', nome: '6ª Vara do Trabalho de Ribeirão Preto' },
  { codigo: '188', nome: '5ª Vara do Trabalho de Jundiaí' },
  { codigo: '201', nome: 'Corregedoria-Geral' },
  { codigo: '401', nome: 'Divisão de Execução de Araçatuba' },
  { codigo: '402', nome: 'DIVEX - Araraquara' },
  { codigo: '403', nome: 'DIVEX - Bauru' },
  { codigo: '404', nome: 'DIVEX - Campinas' },
  { codigo: '405', nome: 'Divisão de Execução de Franca' },
  { codigo: '406', nome: 'DIVEX - Jundiaí' },
  { codigo: '407', nome: 'Divisão de Execução de Limeira' },
  { codigo: '408', nome: 'DIVEX - Piracicaba' },
  { codigo: '409', nome: 'DIVEX - Presidente Prudente' },
  { codigo: '410', nome: 'DIVEX - Ribeirão Preto' },
  { codigo: '411', nome: 'DIVEX - São José dos Campos' },
  { codigo: '412', nome: 'DIVEX - São José do Rio Preto' },
  { codigo: '413', nome: 'DIVEX - Sorocaba' },
  { codigo: '414', nome: 'Divisão de Execução de Taubaté' },
  { codigo: '415', nome: 'LIQ2 - Bauru' },
  { codigo: '416', nome: 'LIQ1 - Campinas' },
  { codigo: '417', nome: 'LIQ1 - São José do Rio Preto' },
  { codigo: '418', nome: 'LIQ1 - Sorocaba' },
  { codigo: '419', nome: 'CON2 - Bauru' },
  { codigo: '420', nome: 'CON2 - Campinas' },
  { codigo: '421', nome: 'CON2 - São José do Rio Preto' },
  { codigo: '422', nome: 'CON2 - Sorocaba' },
  { codigo: '423', nome: 'EXE2 - Bauru' },
  { codigo: '424', nome: 'EXE1 - Campinas' },
  { codigo: '425', nome: 'EXE1 - São José do Rio Preto' },
  { codigo: '426', nome: 'EXE1 - Sorocaba' },
  { codigo: '427', nome: 'EXE4 - Bauru' },
  { codigo: '428', nome: 'EXE5 - Campinas' },
  { codigo: '429', nome: 'EXE3 - São José do Rio Preto' },
  { codigo: '430', nome: 'EXE2 - Sorocaba' },
  { codigo: '431', nome: 'EXE3 - Campinas' },
  { codigo: '432', nome: 'EXE4 - Campinas' },
  { codigo: '433', nome: 'EXE1 - Jundiaí' },
  { codigo: '434', nome: 'EXE2 - Jundiaí' },
  { codigo: '435', nome: 'LIQ1 - Jundiaí' },
  { codigo: '436', nome: 'CON1 - Jundiaí' },
  { codigo: '437', nome: 'CON2 - Jundiaí' },
  { codigo: '438', nome: 'EXE2 - Campinas' },
  { codigo: '439', nome: 'CON1 - São José dos Campos' },
  { codigo: '440', nome: 'EXE1 - São José dos Campos' },
  { codigo: '441', nome: 'EXE2 - São José dos Campos' },
  { codigo: '442', nome: 'EXE4 - São José dos Campos' },
  { codigo: '443', nome: 'LIQ1 - São José dos Campos' },
  { codigo: '444', nome: 'CON1 - Piracicaba' },
  { codigo: '445', nome: 'EXE1 - Piracicaba' },
  { codigo: '446', nome: 'LIQ1 - Piracicaba' },
  { codigo: '447', nome: 'CON1 - Araraquara' },
  { codigo: '448', nome: 'EXE1 - Araraquara' },
  { codigo: '449', nome: 'LIQ2 - Araraquara' },
  { codigo: '450', nome: 'CON2 - Ribeirão Preto' },
  { codigo: '451', nome: 'LIQ1 - Ribeirão Preto' },
  { codigo: '453', nome: 'EXE2 - São José do Rio Preto' },
  { codigo: '454', nome: 'EXE6 - Campinas' },
  { codigo: '455', nome: 'LIQ2 - Ribeirão Preto' },
  { codigo: '456', nome: 'EXE4 - São José do Rio Preto' },
  { codigo: '457', nome: 'CON1 - Ribeirão Preto' },
  { codigo: '458', nome: 'EXE1 - Ribeirão Preto' },
  { codigo: '459', nome: 'EXE2 - Ribeirão Preto' },
  { codigo: '460', nome: 'EXE4 - Ribeirão Preto' },
  { codigo: '461', nome: 'DAM - Araraquara' },
  { codigo: '462', nome: 'DAM - Bauru' },
  { codigo: '463', nome: 'DAM - Campinas' },
  { codigo: '464', nome: 'DAM - Jundiaí' },
  { codigo: '465', nome: 'DAM - Piracicaba' },
  { codigo: '466', nome: 'DAM - Ribeirão Preto' },
  { codigo: '467', nome: 'DAM - São José do Rio Preto' },
  { codigo: '468', nome: 'DAM - São José dos Campos' },
  { codigo: '469', nome: 'Divisão de Apoio aos Magistrados de Sertãozinho' },
  { codigo: '470', nome: 'DAM - Sorocaba' },
  { codigo: '471', nome: 'Assessoria de Execução I de Sertãozinho, Orlândia, Batatais e Franca' },
  { codigo: '472', nome: 'Assessoria de Execução II de Sertãozinho, Orlândia, Batatais e Franca' },
  { codigo: '473', nome: 'EXE3 - Ribeirão Preto' },
  { codigo: '474', nome: 'EXE1 - Bauru' },
  { codigo: '475', nome: 'EXE2 - Araraquara' },
  { codigo: '476', nome: 'EXE3 - Araraquara' },
  { codigo: '477', nome: 'EXE4 - Araraquara' },
  { codigo: '478', nome: 'LIQ2 - Campinas' },
  { codigo: '479', nome: 'EXE2 - Piracicaba' },
  { codigo: '480', nome: 'EXE4 - Piracicaba' },
  { codigo: '481', nome: 'CON1 - São José do Rio Preto' },
  { codigo: '482', nome: 'LIQ2 - São José do Rio Preto' },
  { codigo: '483', nome: 'EXE4 - Sorocaba' },
  { codigo: '484', nome: 'LIQ2 - Piracicaba' },
  { codigo: '485', nome: 'EXE3 - Piracicaba' },
  { codigo: '486', nome: 'CON2 - Piracicaba' },
  { codigo: '487', nome: 'EXE3 - Sorocaba' },
  { codigo: '488', nome: 'LIQ2 - Sorocaba' },
  { codigo: '489', nome: 'CON1 - Sorocaba' },
  { codigo: '490', nome: 'CON2 - Araraquara' },
  { codigo: '491', nome: 'LIQ1 - Araraquara' },
  { codigo: '492', nome: 'CON1 - Bauru' },
  { codigo: '493', nome: 'LIQ1 - Bauru' },
  { codigo: '494', nome: 'EXE3 - Bauru' },
  { codigo: '495', nome: 'CON1 - Campinas' },
  { codigo: '496', nome: 'LIQ2 - Jundiaí' },
  { codigo: '497', nome: 'EXE3 - Jundiaí' },
  { codigo: '498', nome: 'EXE4 - Jundiaí' },
  { codigo: '499', nome: 'CON2 - São José dos Campos' },
  { codigo: '500', nome: 'EXE3 - São José dos Campos' },
  { codigo: '501', nome: 'LIQ2 - São José dos Campos' },
  { codigo: '502', nome: 'CON1 - Presidente Prudente' },
  { codigo: '503', nome: 'CON2 - Presidente Prudente' },
  { codigo: '504', nome: 'LIQ1 - Presidente Prudente' },
  { codigo: '505', nome: 'LIQ2 - Presidente Prudente' },
  { codigo: '506', nome: 'EXE1 - Presidente Prudente' },
  { codigo: '507', nome: 'EXE2 - Presidente Prudente' },
  { codigo: '508', nome: 'EXE3 - Presidente Prudente' },
  { codigo: '509', nome: 'EXE4 - Presidente Prudente' },
  { codigo: '510', nome: 'DAM - Presidente Prudente' },
  { codigo: '601', nome: 'Órgão Centralizador de Leilões Judiciais de Araçatuba' },
  { codigo: '602', nome: 'Órgão Centralizador de Leilões Judiciais de Araraquara' },
  { codigo: '603', nome: 'Órgão Centralizador de Leilões Judiciais de Bauru' },
  { codigo: '604', nome: 'Órgão Centralizador de Leilões Judiciais de Campinas' },
  { codigo: '605', nome: 'Órgão Centralizador de Leilões Judiciais de Franca' },
  { codigo: '606', nome: 'Órgão Centralizador de Leilões Judiciais de Jundiaí' },
  { codigo: '607', nome: 'Órgão Centralizador de Leilões Judiciais de Limeira' },
  { codigo: '608', nome: 'Órgão Centralizador de Leilões Judiciais de Piracicaba' },
  { codigo: '609', nome: 'Órgão Centralizador de Leilões Judiciais de Presidente Prudente' },
  { codigo: '610', nome: 'Órgão Centralizador de Leilões Judiciais de Ribeirão Preto' },
  { codigo: '611', nome: 'Órgão Centralizador de Leilões Judiciais de São José do Rio Preto' },
  { codigo: '612', nome: 'Órgão Centralizador de Leilões Judiciais de São José dos Campos' },
  { codigo: '613', nome: 'Órgão Centralizador de Leilões Judiciais de Sorocaba' },
  { codigo: '614', nome: 'Órgão Centralizador de Leilões Judiciais de Taubaté' },
  { codigo: '615', nome: 'CEJUSC ARAÇATUBA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '616', nome: 'CEJUSC BAURU - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '617', nome: 'CEJUSC CAMPINAS - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '618', nome: 'CEJUSC PRESIDENTE PRUDENTE - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '619', nome: 'CEJUSC RIBEIRÃO PRETO - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '620', nome: 'CEJUSC SJCAMPOS - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '621', nome: 'CEJUSC SJRIO PRETO - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '622', nome: 'CEJUSC SOROCABA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '623', nome: 'CEJUSC ARARAQUARA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '624', nome: 'CEJUSC FRANCA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '625', nome: 'CEJUSC LIMEIRA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '626', nome: 'CEJUSC PIRACICABA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '627', nome: 'CEJUSC JUNDIAÍ - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '628', nome: 'CEJUSC TAUBATÉ - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho' },
  { codigo: '629', nome: 'Juizado Especial da Infância e Adolescência de Araçatuba' },
  { codigo: '630', nome: 'Juizado Especial da Infância e Adolescência de Bauru' },
  { codigo: '631', nome: 'Juizado Especial da Infância e Adolescência de Campinas' },
  { codigo: '632', nome: 'Juizado Especial da Infância e Adolescência de Fernandópolis' },
  { codigo: '633', nome: 'Juizado Especial da Infância e Adolescência de Franca' },
  { codigo: '634', nome: 'Juizado Especial da Infância e Adolescência de Presidente Prudente' },
  { codigo: '635', nome: 'Juizado Especial da Infância e Adolescência de Ribeirão Preto' },
  { codigo: '636', nome: 'Juizado Especial da Infância e Adolescência de Sorocaba' },
  { codigo: '637', nome: 'Juizado Especial da Infância e Adolescência de São José do Rio Preto' },
  { codigo: '638', nome: 'Juizado Especial da Infância e Adolescência de São José dos Campos' },
  { codigo: '900', nome: '1º Núcleo de Justiça 4.0' },
  { codigo: '901', nome: 'Posto Avançado da Justiça do Trabalho de Amparo em Pedreira' },
  { codigo: '902', nome: 'Posto Avançado da Justiça do Trabalho de Andradina em Pereira Barreto' },
  { codigo: '903', nome: 'Posto Avançado da Justiça do Trabalho de Araraquara em Américo Brasiliense' },
  { codigo: '904', nome: 'Justiça Itinerante/Posto Avançado da Justiça do Trabalho de Ituverava em Igarapava' },
  { codigo: '905', nome: 'Posto Avançado da Justiça do Trabalho de Jundiaí em Vinhedo' },
  { codigo: '906', nome: 'Posto Avançado da Justiça do Trabalho de Orlândia em Morro Agudo' },
  { codigo: '907', nome: 'Posto Avançado da Justiça do Trabalho de Pederneiras em Bariri' },
  { codigo: '908', nome: 'Posto Avançado da Justiça do Trabalho de Pindamonhangaba em Campos do Jordão' },
  { codigo: '909', nome: 'Posto Avançado da Justiça do Trabalho de São João da Boa Vista em Espírito Santo Do Pinhal' },
  { codigo: '910', nome: 'Posto Avançado da Justiça do Trabalho de Campinas em Valinhos' },
  { codigo: '1000', nome: 'Posto Avançado da Justiça do Trabalho da 15ª Região' },
  { codigo: '1901', nome: 'CCP ARARAQUARA - Centro de Conciliação Pré Processual' },
  { codigo: '1902', nome: 'CCP ARAÇATUBA - Centro de Conciliação Pré Processual' },
  { codigo: '1903', nome: 'CCP BAURU - Centro de Conciliação Pré Processual' },
  { codigo: '1904', nome: 'CCP CAMPINAS - Centro de Conciliação Pré Processual' },
  { codigo: '1905', nome: 'CCP FRANCA - Centro de Conciliação Pré Processual' },
  { codigo: '1906', nome: 'CCP JUNDIAÍ - Centro de Conciliação Pré Processual' },
  { codigo: '1907', nome: 'CCP LIMEIRA - Centro de Conciliação Pré Processual' },
  { codigo: '1908', nome: 'CCP PIRACICABA - Centro de Conciliação Pré Processual' },
  { codigo: '1909', nome: 'CCP PRESIDENTE PRUDENTE - Centro de Conciliação Pré Processual' },
  { codigo: '1910', nome: 'CCP RIBEIRÃO PRETO - Centro de Conciliação Pré Processual' },
  { codigo: '1911', nome: 'CCP SOROCABA - Centro de Conciliação Pré Processual' },
  { codigo: '1912', nome: 'CCP SÃO JOSÉ DO RIO PRETO - Centro de Conciliação Pré Processual' },
  { codigo: '1913', nome: 'CCP SÃO JOSÉ DOS CAMPOS - Centro de Conciliação Pré Processual' },
  { codigo: '1914', nome: 'CCP TAUBATÉ - Centro de Conciliação Pré Processual' },
  { codigo: '1915', nome: 'CCP DE 2º GRAU - Centro de Conciliação Pré Processual' }
];

export const tiposPendencia = [
  'Erro de Sistema',
  'Falha de Integração',
  'Problema de Performance',
  'Erro de Configuração',
  'Falha de Funcionalidade',
  'Erro de Validação',
  'Problema de Acesso',
  'Outros'
];

export const urgencias = [
  'Crítica',
  'Alta',
  'Média',
  'Baixa'
];

export const subsistemas = [
  'PJe 1º Grau',
  'PJe 2º Grau',
  'PJe Administrativo',
  'PJe Execução',
  'Integração SERASAJUD',
  'Integração BACENJUD',
  'Integração RENAJUD',
  'Outros'
];

export const ambientes = [
  'Produção',
  'Homologação',
  'Desenvolvimento',
  'Treinamento'
];

export const resumosPadroes = [
  'Acesso ao Sistema – Erro ao Carregar Painel',
  'Acórdão – Erro',
  'Acumulador – Consulta de Posição',
  'Acumulador – Regularização',
  'Advogado – Painel do Advogado / Procurador – Erro',
  'Agrupadores – Erro',
  'Área de Zoneamento – Erro em Configuração do Oficial de Justiça',
  'Assinador não Carrega – Não ativa o botão "Entrar"',
  'Assinatura de Acórdão – Erro',
  'Assinatura de Ata – Erro',
  'Assuntos da Ação – Competência',
  'Assuntos da Ação – Inexistência',
  'Ata de Audiência – Erro de Assinatura',
  'Ata de Audiência – Erro na Confirmação',
  'Ata de Audiência – Erro na Exportação',
  'Atualização de Tela',
  'Audiência – Pauta – Erro de Designação',
  'Audiências – Erro ao Abrir Pauta',
  'Audiências – Erro Configuração de Sala',
  'Audiências – Pauta Bloqueada – Marcação de Horário',
  'Autenticação: Erro ao Consultar Dados',
  'Autenticação: Não foi Possível Realizar',
  'Atuação – Correção de Parte',
  'Atuação – Erro ao Alterar a Classe',
  'Baixa ao 1º Grau – Erro',
  'Baixa de Documentos – Erro Webservice',
  'Baixa para diligência – Erro',
  'BNDT – Erro na Inclusão ou Exclusão',
  'Cadastro de Advogado – Erro',
  'Cadastro de Autoridade',
  'Cadastro de Magistrado – Alteração',
  'Cadastro de Órgãos Públicos',
  'Cadastro de Perito – Erro',
  'Cadastro de Pessoa Física – Atualização de Nome',
  'Cadastro de Pessoa Física – Erro',
  'Cadastro de Pessoa Jurídica – Erro',
  'Cadastro de Processo CLE – Erro na Elaboração',
  'Cadastro de Procurador – Erro',
  'Cadastro de Usuário – Correção de Perfil',
  'Cadastro de Usuário – Exclusão de Perfil',
  'Calendário',
  'Caixas das Árvores de Tarefa – Erro na listagem',
  'CEP – Registro Ausente',
  'CEP Inexistente na Base dos Correios – Não Encontrado',
  'Certidão de Distribuição de Ações Trabalhistas',
  'Competência – Classe × Assunto',
  'Competência – Órgão Julgador × Competência',
  'Configuração de Órgão Julgador',
  'Configuração do Sistema – Alteração, Inclusão ou Exclusão',
  'Consulta – Alertas em Processos – Erro',
  'Consulta Características / Recursos do Sistema',
  'Consulta de Processos',
  'Controle de prazos – Erro',
  'Decisão / Despacho – Erro na Assinatura',
  'Defeito em Homologação',
  'Defeito em Produção',
  'Descrição de Tipo de Parte – Erro – Classe Judicial',
  'Distribuição de Processos – Erro',
  'Documento – Sem Conteúdo',
  'Documento do Processo – Erro ao Abrir',
  'Documento do Processo – Erro ao Salvar',
  'Documento do Processo – Erro em Assinatura',
  'Documento do Processo – Erro no Escaninho',
  'Documento do Processo – Sem Assinatura',
  'Documento do Processo – Sem Data de Juntada',
  'Documentos – Aba Anexar Documentos – Tipos',
  'Documentos – Anexos – Sem Vinculação com o Principal',
  'Documentos – Exclusão',
  'Documentos do Processo – Erro ao Baixar',
  'Documentos do Processo – Erro na Atualização',
  'Documentos do Processo – Erro no Tipo – Despacho',
  'E-Rec – Configuração – Erro',
  'EXE-Pje – Erro de Execução',
  'GIGS – Erro',
  'Habilitação Advogado – Erro',
  'Inclusão de CEP',
  'JIRA 1º grau – Consulta de Mensagens',
  'JIRA 1º grau – Postar Mensagem',
  'JIRA 2º grau – Consulta de Mensagens',
  'JIRA 2º grau – Postar Mensagem',
  'Logs do Sistema – Solicitação',
  'MNI – Erro na Assinatura de Documentos',
  'Modelos de Documentos – Erro na Exibição / Seleção',
  'Movimento – Erro no Registro',
  'Nó de Desvio – Erro na Inclusão de Processo',
  'Nó de Desvio – Inexistência de Fluxo',
  'Painel KZ – Filtros',
  'Pauta de Julgamento – Fechamento – Erro',
  'Pauta de Julgamento – Inclusão de Processos – Erro',
  'Pauta de Julgamento – Listagem – Erro',
  'Pauta de Julgamento – Movimentação de Processos – Erro',
  'Pauta de Julgamento – Retirada de Processos – Erro',
  'Processo – Arquivo – Erro ao Vincular',
  'Processo – Arquivo – Erro na Pesquisa',
  'Processo – Arquivo – Erro na Transferência',
  'Processo – Código de Validação',
  'Processo – Consulta de Fluxo',
  'Processo – Consulta Rápida',
  'Processo – Consulta Simples',
  'Processo – Desentranhamento',
  'Processo – Erro ao Enviar',
  'Processo – Erro ao Mover',
  'Processo – Erro de Distribuição',
  'Processo – Erro de Numeração',
  'Processo – Histórico – Erro na Visualização',
  'Processo – Localização – Erro na Consulta',
  'Processo – Petição Inicial – Erro ao Visualizar',
  'Processo – Remessa – Erro no Envio',
  'Processo – Tarefa – Erro na Assinatura',
  'Processo – Tarefa – Erro na Designação',
  'Processo – Tarefa – Erro na Tramitação',
  'Processo – Tarefa – Erro no Registro',
  'Processo – Transferência – Erro',
  'Processo – Vista de Partes – Erro ao Abrir',
  'Relatório – Erro na Emissão',
  'Relatório – Erro na Seleção',
  'Relatório – Falha no Formato / Filtros',
  'Relatório – Falha no Sistema',
  'Sistema – Configuração de Correios',
  'Sistema – Configuração de Pauta',
  'Sistema – Configuração de Protocolo',
  'Sistema – Configuração de Tarefa',
  'Sistema – Erro de Autenticação',
  'Sistema – Erro de Cache',
  'Sistema – Erro de Comunicação',
  'Sistema – Erro de Conexão',
  'Sistema – Falha de Interface',
  'Sistema – Falha de Performance',
  'Sistema – Instabilidade',
  'Sistema – Lentidão',
  'Sistema – Manutenção Programada',
  'Sistema – Parametrização – Erro',
  'Sistema – Protocolo – Erro',
  'Sistema – Timeout – Erro',
  'Sistema – Timeout de Sessão',
  'Tarefa – Análise – Erro ao processar',
  'Tarefa – Distribuição – Erro no processamento',
  'Tarefa – Expedição – Erro ao incluir',
  'Tarefa – Expedição – Erro ao visualizar',
  'Tarefa – Juntar Petição – Erro',
  'Tarefa – Minuta – Erro ao editar',
  'Tarefa – Processo – Análise de Dependência'
];