-- Inserir dados adicionais do 1º grau (ignorando duplicatas)
INSERT INTO public.orgaos_julgadores_1grau (codigo, nome) VALUES
('495', 'CON1 - Campinas'),
('436', 'CON1 - Jundiaí'),
('444', 'CON1 - Piracicaba'),
('502', 'CON1 - Presidente Prudente'),
('457', 'CON1 - Ribeirão Preto'),
('489', 'CON1 - Sorocaba'),
('481', 'CON1 - São José do Rio Preto'),
('439', 'CON1 - São José dos Campos'),
('490', 'CON2 - Araraquara'),
('419', 'CON2 - Bauru'),
('420', 'CON2 - Campinas'),
('437', 'CON2 - Jundiaí'),
('486', 'CON2 - Piracicaba'),
('503', 'CON2 - Presidente Prudente'),
('450', 'CON2 - Ribeirão Preto'),
('422', 'CON2 - Sorocaba'),
('421', 'CON2 - São José do Rio Preto'),
('499', 'CON2 - São José dos Campos'),
('112', 'Vara do Trabalho de Cajuru'),
('129', '10ª Vara do Trabalho de Campinas'),
('130', '11ª Vara do Trabalho de Campinas'),
('131', '12ª Vara do Trabalho de Campinas'),
('1', '1ª Vara do Trabalho de Campinas'),
('32', '2ª Vara do Trabalho de Campinas'),
('43', '3ª Vara do Trabalho de Campinas'),
('53', '4ª Vara do Trabalho de Campinas'),
('92', '5ª Vara do Trabalho de Campinas'),
('93', '6ª Vara do Trabalho de Campinas'),
('94', '7ª Vara do Trabalho de Campinas'),
('95', '8ª Vara do Trabalho de Campinas'),
('114', '9ª Vara do Trabalho de Campinas'),
('631', 'Juizado Especial da Infância e Adolescência de Campinas'),
('604', 'Órgão Centralizador de Leilões Judiciais de Campinas'),
('910', 'Posto Avançado da Justiça do Trabalho de Campinas em Valinhos'),
('105', 'Vara do Trabalho de Campo Limpo Paulista'),
('39', 'Vara do Trabalho de Capivari'),
('123', 'Vara do Trabalho de Capão Bonito'),
('63', 'Vara do Trabalho de Caraguatatuba'),
('28', '1ª Vara do Trabalho de Catanduva'),
('70', '2ª Vara do Trabalho de Catanduva'),
('119', 'Vara do Trabalho de Caçapava'),
('1901', 'CCP ARARAQUARA - Centro de Conciliação Pré Processual'),
('1902', 'CCP ARAÇATUBA - Centro de Conciliação Pré Processual'),
('1903', 'CCP BAURU - Centro de Conciliação Pré Processual'),
('1904', 'CCP CAMPINAS - Centro de Conciliação Pré Processual'),
('1915', 'CCP DE 2º GRAU - Centro de Conciliação Pré Processual'),
('1905', 'CCP FRANCA - Centro de Conciliação Pré Processual'),
('1906', 'CCP JUNDIAÍ - Centro de Conciliação Pré Processual'),
('1907', 'CCP LIMEIRA - Centro de Conciliação Pré Processual'),
('1908', 'CCP PIRACICABA - Centro de Conciliação Pré Processual'),
('1909', 'CCP PRESIDENTE PRUDENTE - Centro de Conciliação Pré Processual'),
('1910', 'CCP RIBEIRÃO PRETO - Centro de Conciliação Pré Processual'),
('1911', 'CCP SOROCABA - Centro de Conciliação Pré Processual'),
('1912', 'CCP SÃO JOSÉ DO RIO PRETO - Centro de Conciliação Pré Processual'),
('1913', 'CCP SÃO JOSÉ DOS CAMPOS - Centro de Conciliação Pré Processual'),
('1914', 'CCP TAUBATÉ - Centro de Conciliação Pré Processual'),
('201', 'Corregedoria-Geral'),
('150', 'Vara do Trabalho de Cravinhos'),
('40', 'Vara do Trabalho de Cruzeiro'),
('461', 'DAM - Araraquara'),
('462', 'DAM - Bauru'),
('463', 'DAM - Campinas'),
('464', 'DAM - Jundiaí'),
('465', 'DAM - Piracicaba'),
('510', 'DAM - Presidente Prudente'),
('466', 'DAM - Ribeirão Preto'),
('470', 'DAM - Sorocaba'),
('467', 'DAM - São José do Rio Preto'),
('468', 'DAM - São José dos Campos'),
('402', 'DIVEX - Araraquara'),
('403', 'DIVEX - Bauru'),
('404', 'DIVEX - Campinas'),
('406', 'DIVEX - Jundiaí'),
('408', 'DIVEX - Piracicaba'),
('409', 'DIVEX - Presidente Prudente'),
('410', 'DIVEX - Ribeirão Preto'),
('413', 'DIVEX - Sorocaba'),
('412', 'DIVEX - São José do Rio Preto'),
('411', 'DIVEX - São José dos Campos'),
('623', 'CEJUSC ARARAQUARA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('615', 'CEJUSC ARAÇATUBA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('616', 'CEJUSC BAURU - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('617', 'CEJUSC CAMPINAS - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('624', 'CEJUSC FRANCA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('627', 'CEJUSC JUNDIAÍ - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('625', 'CEJUSC LIMEIRA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('626', 'CEJUSC PIRACICABA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('618', 'CEJUSC PRESIDENTE PRUDENTE - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('619', 'CEJUSC RIBEIRÃO PRETO - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('620', 'CEJUSC SJCAMPOS - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('621', 'CEJUSC SJRIO PRETO - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('622', 'CEJUSC SOROCABA - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('628', 'CEJUSC TAUBATÉ - JT Centro Judiciário de Métodos Consensuais de Solução de Disputas da Justiça do Trabalho'),
('50', 'Vara do Trabalho de Dracena'),
('448', 'EXE1 - Araraquara'),
('474', 'EXE1 - Bauru'),
('424', 'EXE1 - Campinas'),
('433', 'EXE1 - Jundiaí'),
('445', 'EXE1 - Piracicaba'),
('506', 'EXE1 - Presidente Prudente'),
('458', 'EXE1 - Ribeirão Preto'),
('426', 'EXE1 - Sorocaba'),
('425', 'EXE1 - São José do Rio Preto'),
('440', 'EXE1 - São José dos Campos'),
('475', 'EXE2 - Araraquara'),
('423', 'EXE2 - Bauru'),
('438', 'EXE2 - Campinas'),
('434', 'EXE2 - Jundiaí'),
('479', 'EXE2 - Piracicaba'),
('507', 'EXE2 - Presidente Prudente'),
('459', 'EXE2 - Ribeirão Preto'),
('430', 'EXE2 - Sorocaba'),
('453', 'EXE2 - São José do Rio Preto'),
('441', 'EXE2 - São José dos Campos'),
('476', 'EXE3 - Araraquara'),
('494', 'EXE3 - Bauru'),
('431', 'EXE3 - Campinas'),
('497', 'EXE3 - Jundiaí'),
('485', 'EXE3 - Piracicaba'),
('508', 'EXE3 - Presidente Prudente'),
('473', 'EXE3 - Ribeirão Preto'),
('487', 'EXE3 - Sorocaba'),
('429', 'EXE3 - São José do Rio Preto'),
('500', 'EXE3 - São José dos Campos'),
('477', 'EXE4 - Araraquara'),
('427', 'EXE4 - Bauru'),
('432', 'EXE4 - Campinas'),
('498', 'EXE4 - Jundiaí'),
('480', 'EXE4 - Piracicaba'),
('509', 'EXE4 - Presidente Prudente'),
('460', 'EXE4 - Ribeirão Preto'),
('483', 'EXE4 - Sorocaba'),
('456', 'EXE4 - São José do Rio Preto'),
('442', 'EXE4 - São José dos Campos'),
('428', 'EXE5 - Campinas'),
('454', 'EXE6 - Campinas'),
('632', 'Juizado Especial da Infância e Adolescência de Fernandópolis'),
('37', 'Vara do Trabalho de Fernandópolis'),
('15', '1ª Vara do Trabalho de Franca'),
('76', '2ª Vara do Trabalho de Franca'),
('405', 'Divisão de Execução de Franca'),
('633', 'Juizado Especial da Infância e Adolescência de Franca'),
('605', 'Órgão Centralizador de Leilões Judiciais de Franca'),
('98', 'Vara do Trabalho de Garça'),
('20', 'Vara do Trabalho de Guaratinguetá'),
('152', 'Vara do Trabalho de Hortolândia'),
('77', 'Vara do Trabalho de Indaiatuba'),
('64', 'Vara do Trabalho de Itanhaém'),
('41', 'Vara do Trabalho de Itapetininga'),
('47', 'Vara do Trabalho de Itapeva'),
('118', 'Vara do Trabalho de Itapira'),
('148', 'Vara do Trabalho de Itararé'),
('145', 'Vara do Trabalho de Itatiba'),
('18', 'Vara do Trabalho de Itu'),
('52', 'Vara do Trabalho de Ituverava'),
('904', 'Justiça Itinerante/Posto Avançado da Justiça do Trabalho de Ituverava em Igarapava'),
('49', 'Vara do Trabalho de Itápolis'),
('29', '1ª Vara do Trabalho de Jaboticabal'),
('120', '2ª Vara do Trabalho de Jaboticabal'),
('23', '1ª Vara do Trabalho de Jacareí'),
('138', '2ª Vara do Trabalho de Jacareí'),
('80', 'Vara do Trabalho de Jales'),
('24', '1ª Vara do Trabalho de Jaú'),
('55', '2ª Vara do Trabalho de Jaú'),
('110', 'Vara do Trabalho de José Bonifácio'),
('2', '1ª Vara do Trabalho de Jundiaí'),
('21', '2ª Vara do Trabalho de Jundiaí'),
('96', '3ª Vara do Trabalho de Jundiaí'),
('97', '4ª Vara do Trabalho de Jundiaí'),
('188', '5ª Vara do Trabalho de Jundiaí'),
('606', 'Órgão Centralizador de Leilões Judiciais de Jundiaí'),
('905', 'Posto Avançado da Justiça do Trabalho de Jundiaí em Vinhedo'),
('900', '1º Núcleo de Justiça 4.0'),
('491', 'LIQ1 - Araraquara'),
('493', 'LIQ1 - Bauru'),
('416', 'LIQ1 - Campinas'),
('435', 'LIQ1 - Jundiaí'),
('446', 'LIQ1 - Piracicaba'),
('504', 'LIQ1 - Presidente Prudente'),
('451', 'LIQ1 - Ribeirão Preto'),
('418', 'LIQ1 - Sorocaba'),
('417', 'LIQ1 - São José do Rio Preto'),
('443', 'LIQ1 - São José dos Campos'),
('449', 'LIQ2 - Araraquara'),
('415', 'LIQ2 - Bauru'),
('478', 'LIQ2 - Campinas'),
('496', 'LIQ2 - Jundiaí'),
('484', 'LIQ2 - Piracicaba'),
('505', 'LIQ2 - Presidente Prudente'),
('455', 'LIQ2 - Ribeirão Preto'),
('488', 'LIQ2 - Sorocaba'),
('482', 'LIQ2 - São José do Rio Preto'),
('501', 'LIQ2 - São José dos Campos'),
('134', 'Vara do Trabalho de Leme'),
('74', '1ª Vara do Trabalho de Lençóis Paulista'),
('149', '2ª Vara do Trabalho de Lençóis Paulista'),
('14', '1ª Vara do Trabalho de Limeira'),
('128', '2ª Vara do Trabalho de Limeira'),
('407', 'Divisão de Execução de Limeira'),
('607', 'Órgão Centralizador de Leilões Judiciais de Limeira'),
('62', 'Vara do Trabalho de Lins'),
('88', 'Vara do Trabalho de Lorena'),
('33', '1ª Vara do Trabalho de Marília'),
('101', '2ª Vara do Trabalho de Marília'),
('81', 'Vara do Trabalho de Matão'),
('141', 'Vara do Trabalho de Mococa'),
('71', 'Vara do Trabalho de Mogi Guaçu'),
('22', 'Vara do Trabalho de Mogi Mirim'),
('107', 'Vara do Trabalho de Olímpia'),
('146', 'Vara do Trabalho de Orlândia'),
('906', 'Posto Avançado da Justiça do Trabalho de Orlândia em Morro Agudo'),
('30', 'Vara do Trabalho de Ourinhos'),
('87', '1ª Vara do Trabalho de Paulínia'),
('126', '2ª Vara do Trabalho de Paulínia'),
('144', 'Vara do Trabalho de Pederneiras'),
('907', 'Posto Avançado da Justiça do Trabalho de Pederneiras em Bariri'),
('124', 'Vara do Trabalho de Penápolis'),
('78', 'Vara do Trabalho de Piedade'),
('59', 'Vara do Trabalho de Pindamonhangaba'),
('908', 'Posto Avançado da Justiça do Trabalho de Pindamonhangaba em Campos do Jordão'),
('12', '1ª Vara do Trabalho de Piracicaba'),
('51', '2ª Vara do Trabalho de Piracicaba'),
('137', '3ª Vara do Trabalho de Piracicaba'),
('608', 'Órgão Centralizador de Leilões Judiciais de Piracicaba'),
('136', 'Vara do Trabalho de Pirassununga'),
('48', 'Vara do Trabalho de Porto Ferreira'),
('1000', 'Posto Avançado da Justiça do Trabalho da 15ª Região'),
('26', '1ª Vara do Trabalho de Presidente Prudente'),
('115', '2ª Vara do Trabalho de Presidente Prudente'),
('634', 'Juizado Especial da Infância e Adolescência de Presidente Prudente'),
('609', 'Órgão Centralizador de Leilões Judiciais de Presidente Prudente'),
('57', 'Vara do Trabalho de Presidente Venceslau'),
('72', 'Vara do Trabalho de Rancharia'),
('69', 'Vara do Trabalho de Registro'),
('4', '1ª Vara do Trabalho de Ribeirão Preto'),
('42', '2ª Vara do Trabalho de Ribeirão Preto'),
('66', '3ª Vara do Trabalho de Ribeirão Preto'),
('67', '4ª Vara do Trabalho de Ribeirão Preto'),
('113', '5ª Vara do Trabalho de Ribeirão Preto'),
('153', '6ª Vara do Trabalho de Ribeirão Preto'),
('635', 'Juizado Especial da Infância e Adolescência de Ribeirão Preto'),
('610', 'Órgão Centralizador de Leilões Judiciais de Ribeirão Preto'),
('10', 'Vara do Trabalho de Rio Claro'),
('85', 'Vara do Trabalho de Salto'),
('86', 'Vara do Trabalho de Santa Bárbara D''Oeste'),
('143', 'Vara do Trabalho de Santa Cruz do Rio Pardo'),
('54', '1ª Vara do Trabalho de Sertãozinho'),
('125', '2ª Vara do Trabalho de Sertãozinho'),
('469', 'Divisão de Apoio aos Magistrados de Sertãozinho'),
('471', 'Assessoria de Execução I de Sertãozinho, Orlândia, Batatais e Franca'),
('472', 'Assessoria de Execução II de Sertãozinho, Orlândia, Batatais e Franca'),
('3', '1ª Vara do Trabalho de Sorocaba'),
('16', '2ª Vara do Trabalho de Sorocaba'),
('109', '3ª Vara do Trabalho de Sorocaba'),
('135', '4ª Vara do Trabalho de Sorocaba'),
('636', 'Juizado Especial da Infância e Adolescência de Sorocaba'),
('613', 'Órgão Centralizador de Leilões Judiciais de Sorocaba'),
('122', 'Vara do Trabalho de Sumaré'),
('8', '1ª Vara do Trabalho de São Carlos'),
('106', '2ª Vara do Trabalho de São Carlos'),
('117', 'Vara do Trabalho de São Joaquim da Barra'),
('35', 'Vara do Trabalho de São José do Rio Pardo'),
('17', '1ª Vara do Trabalho de São José do Rio Preto'),
('44', '2ª Vara do Trabalho de São José do Rio Preto'),
('82', '3ª Vara do Trabalho de São José do Rio Preto'),
('133', '4ª Vara do Trabalho de São José do Rio Preto'),
('637', 'Juizado Especial da Infância e Adolescência de São José do Rio Preto'),
('611', 'Órgão Centralizador de Leilões Judiciais de São José do Rio Preto'),
('13', '1ª Vara do Trabalho de São José dos Campos'),
('45', '2ª Vara do Trabalho de São José dos Campos'),
('83', '3ª Vara do Trabalho de São José dos Campos'),
('84', '4ª Vara do Trabalho de São José dos Campos'),
('132', '5ª Vara do Trabalho de São José dos Campos'),
('638', 'Juizado Especial da Infância e Adolescência de São José dos Campos'),
('612', 'Órgão Centralizador de Leilões Judiciais de São José dos Campos'),
('34', 'Vara do Trabalho de São João da Boa Vista'),
('909', 'Posto Avançado da Justiça do Trabalho de São João da Boa Vista em Espírito Santo Do Pinhal'),
('108', 'Vara do Trabalho de São Roque'),
('121', 'Vara do Trabalho de São Sebastião'),
('104', 'Vara do Trabalho de Tanabi'),
('142', 'Vara do Trabalho de Taquaritinga'),
('116', 'Vara do Trabalho de Tatuí'),
('9', '1ª Vara do Trabalho de Taubaté'),
('102', '2ª Vara do Trabalho de Taubaté'),
('414', 'Divisão de Execução de Taubaté'),
('614', 'Órgão Centralizador de Leilões Judiciais de Taubaté'),
('127', 'Vara do Trabalho de Teodoro Sampaio'),
('111', 'Vara do Trabalho de Tietê'),
('65', 'Vara do Trabalho de Tupã'),
('139', 'Vara do Trabalho de Ubatuba'),
('27', 'Vara do Trabalho de Votuporanga')
ON CONFLICT (codigo) DO NOTHING;