-- Inserir dados adicionais do 2º grau (ignorando duplicatas)
INSERT INTO public.orgaos_julgadores_2grau (codigo, nome) VALUES
('46', 'Gabinete do Desembargador Orlando Amâncio Taveira - 3ª SDI'),
('297', 'Gabinete do Plantonista'),
('326', 'Gabinete do Desembargador Edison dos Santos Pelegrini - 1ª Câmara'),
('314', 'Gabinete de Desembargador Suplente no Órgão Especial 1'),
('315', 'Gabinete de Desembargador Suplente no Órgão Especial 2'),
('316', 'Gabinete de Desembargador Suplente no Órgão Especial 3'),
('309', 'Vaga Aposent. da Desembargadora Vera Teresa Martins Crespo - 1ª Câmara'),
('101', 'Vaga Aposent. da Desembargadora Vera Teresa Martins Crespo - 3ª SDI'),
('313', 'Vaga Aposent. da Desembargadora Vera Teresa Martins Crespo - 1ª SDI'),
('294', 'Gabinete da Vice-Corregedoria Regional - Presidência 2ª SDI'),
('253', 'Gabinete da Desembargadora Andrea Guelfi Cunha - Tribunal Pleno'),
('139', 'Gabinete da Desembargadora Elency Pereira Neves - 9ª Câmara'),
('550', 'Gabinete do Desembargador Marcelo Garcia Nunes - Órgão Especial'),
('546', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - 3ª SDI'),
('208', 'Gabinete da Desembargadora Suzana Monreal Ramos Nogueira - Tribunal Pleno'),
('525', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - 6ª Câmara'),
('318', 'Vaga Aposent. da Desembargadora Elency Pereira Neves - 9ª Câmara'),
('560', 'Gabinete do Desembargador Representante da 1ª Câmara na SUJ'),
('557', 'Gabinete da Desembargadora Antonia Sant''Ana - 9ª Câmara'),
('401', 'Gabinete do Desembargador Fabio Grasselli - Órgão Especial'),
('551', 'Gabinete do Desembargador João Batista da Silva - 9ª Câmara'),
('306', 'Gabinete do Desembargador João Batista Martins César - 11ª Câmara'),
('310', 'Gabinete do Desembargador João Batista Martins César - Tribunal Pleno'),
('490', 'Gabinete do Desembargador Luiz Felipe Paim da Luz Bruno Lobo - 3ª Câmara'),
('478', 'Gabinete do Desembargador Samuel Hugo Lima - 6ª Câmara'),
('104', 'Gabinete do Desembargador Wilton Borba Canicoba - 3ª SDI'),
('346', 'Gabinete do Desembargador Wilton Borba Canicoba - 9ª Câmara'),
('254', 'Gabinete do Desembargador Luis Henrique Rafael - Tribunal Pleno'),
('81', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - SDC'),
('479', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 10ª Câmara'),
('476', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - Órgão Especial'),
('520', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 6ª Câmara'),
('516', 'Gabinete da Desembargadora Keila Nogueira Silva - 8ª Câmara'),
('303', 'Gabinete da VPJ - SDC Protesto/Oposição'),
('482', 'Vaga Aposent. do Desembargador Flavio Nunes Campos - 11ª Câmara'),
('171', 'Vaga Aposent. do Desembargador Luis Carlos Candido Martins Sotero da Silva - 8ª Câmara'),
('547', 'Gabinete do Desembargador Levi Rosa Tomé - 7ª Câmara'),
('555', 'Gabinete do Desembargador Levi Rosa Tomé - 9ª Câmara'),
('552', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 1ª Câmara'),
('350', 'Gabinete do Desembargador Luis Henrique Rafael - 3ª SDI'),
('327', 'Gabinete do Juiz do Trabalho Convocado - 9ª Câmara'),
('514', 'Gabinete do Desembargador Eder Sivers - 7ª Câmara'),
('454', 'Gabinete da Desembargadora Maria Madalena de Oliveira - Órgão Especial'),
('354', 'Gabinete de Desembargador Suplente no Órgão Especial 5'),
('355', 'Gabinete de Desembargador Suplente no Órgão Especial 6'),
('483', 'Gabinete do Desembargador Claudinei Zapata Marques - 1ª Câmara'),
('163', 'Vaga Aposent. da Desembargadora Rita de Cássia Scagliusi do Carmo - 6ª Câmara'),
('347', 'Gabinete do Desembargador Edison dos Santos Pelegrini - 10ª Câmara'),
('554', 'Gabinete da Desembargadora Antonia Sant''Ana - 10ª Câmara'),
('341', 'Gabinete do Desembargador Edison dos Santos Pelegrini - 9ª Câmara'),
('369', 'Gabinete do Desembargador Edison dos Santos Pelegrini - Órgão Especial'),
('360', 'Gabinete do Desembargador João Batista da Silva - 1ª SDI'),
('549', 'Gabinete do Desembargador Marcelo Garcia Nunes - 10ª Câmara'),
('298', 'Gabinete da Vice-Presidência Judicial'),
('367', 'Gabinete do Desembargador Fábio Allegretti Cooper - Órgão Especial'),
('232', 'Gabinete do Desembargador Marcos da Silva Porto - Tribunal Pleno'),
('238', 'Gabinete do Desembargador Gerson Lacerda Pistori - Tribunal Pleno'),
('365', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - Órgão Especial'),
('342', 'Gabinete do Desembargador Ricardo Antonio de Plato - 1ª Câmara'),
('119', 'Gabinete do Desembargador Ricardo Antonio de Plato - 2ª SDI'),
('177', 'Gabinete do Desembargador Ricardo Antonio de Plato - 9ª Câmara'),
('358', 'Gabinete do Desembargador Ricardo Antonio de Plato - Tribunal Pleno'),
('359', 'Gabinete do Desembargador Ricardo Regis Laraia - Tribunal Pleno'),
('375', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - 7ª Câmara'),
('340', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - 8ª Câmara'),
('362', 'Gabinete do Desembargador Wilton Borba Canicoba - 3ª Câmara'),
('357', 'Gabinete do Desembargador Wilton Borba Canicoba - Tribunal Pleno'),
('485', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - 2ª Câmara'),
('465', 'Gabinete do Desembargador José Carlos Ábile - 1ª Câmara'),
('146', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - 1ª Câmara'),
('472', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - 9ª Câmara'),
('58', 'Vaga Aposent. do Desembargador José Pedro de Camargo Rodrigues de Souza - 2ª SDI'),
('267', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - Tribunal Pleno'),
('480', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - 9ª Câmara'),
('515', 'Gabinete do Desembargador Orlando Amâncio Taveira - 11ª Câmara'),
('518', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - Tribunal Pleno'),
('458', 'Vaga Aposent. do Desembargador Henrique Damiano - 1ª SDI'),
('82', 'Gabinete do Desembargador Claudinei Zapata Marques - 1ª SDI'),
('378', 'Gabinete de Desembargador Suplente no Órgão Especial 7'),
('379', 'Gabinete de Desembargador Suplente no Órgão Especial 8'),
('328', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 6ª Câmara'),
('53', 'Gabinete do Desembargador Dagoberto Nishina de Azevedo - 1ª SDI'),
('383', 'Gabinete de Desembargador Suplente no Órgão Especial 9'),
('519', 'Gabinete do Desembargador Renato Henry Sant''Anna - 4ª Câmara'),
('536', 'Gabinete da Desembargadora Andrea Guelfi Cunha - 8ª Câmara'),
('90', 'Gabinete do Desembargador Eder Sivers - 2ª SDI'),
('52', 'Gabinete do Desembargador Edmundo Fraga Lopes - 3ª SDI'),
('164', 'Gabinete do Desembargador Fabio Grasselli - 10ª Câmara'),
('481', 'Gabinete do Desembargador Renato Henry Sant''Anna - 6ª Câmara'),
('521', 'Gabinete da Desembargadora Mari Angela Pelegrini - 8ª Câmara'),
('115', 'Vaga Aposent. do Desembargador Renato Buratto - 2ª SDI'),
('469', 'Gabinete do Juiz do Trabalho Convocado - 2ª Câmara'),
('54', 'Gabinete do Desembargador Helcio Dantas Lobo Junior - SDC'),
('388', 'Gabinete do Juiz do Trabalho Convocado - 4ª Câmara'),
('464', 'Gabinete do Juiz do Trabalho Convocado - 5ª Câmara'),
('384', 'Gabinete do Juiz do Trabalho Convocado - 8ª Câmara'),
('62', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - 2ª SDI'),
('503', 'Gabinete da Desembargadora Eleonora Bordini Coca - Órgão Especial'),
('538', 'Gabinete do Desembargador José Carlos Ábile - 9ª Câmara'),
('70', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - 1ª SDI'),
('501', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - 1ª Câmara'),
('202', 'Gabinete do Desembargador José Carlos Ábile - Tribunal Pleno'),
('466', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - 3ª Câmara'),
('443', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - Tribunal Pleno'),
('162', 'Gabinete do Desembargador Fábio Bueno de Aguiar - 11ª Câmara'),
('475', 'Gabinete do Desembargador Orlando Amâncio Taveira - 2ª SDI'),
('45', 'Gabinete do Desembargador Renato Henry Sant''Anna - 1ª SDI'),
('561', 'Gabinete do Desembargador Representante da 2ª Câmara na SUJ'),
('493', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 4ª Câmara'),
('527', 'Gabinete do Desembargador Marcos da Silva Porto - 6ª Câmara'),
('522', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 5ª Câmara'),
('539', 'Gabinete do Desembargador Marcos da Silva Porto - 9ª Câmara'),
('537', 'Gabinete do Desembargador Renato Henry Sant''Anna - 1ª Câmara'),
('377', 'Vaga Aposent. do Desembargador Renato Buratto - 6ª Câmara'),
('178', 'Vaga Aposent. do Desembargador Renato Buratto - 7ª Câmara'),
('151', 'Gabinete da Desembargadora Susana Graciela Santiso - 2ª Câmara'),
('534', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 5ª Câmara'),
('92', 'Gabinete da Desembargadora Elency Pereira Neves - 3ª SDI'),
('147', 'Gabinete do Desembargador Levi Rosa Tomé - 5ª Câmara'),
('540', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 9ª Câmara'),
('491', 'Gabinete do Desembargador Fabio Grasselli - 7ª Câmara'),
('165', 'Gabinete do Desembargador Gerson Lacerda Pistori - 9ª Câmara'),
('120', 'Gabinete do Desembargador Gerson Lacerda Pistori - SDC'),
('410', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - 3ª SDI'),
('531', 'Gabinete do Desembargador Edison dos Santos Pelegrini 11ª Câmara'),
('489', 'Gabinete da Desembargadora Andrea Guelfi Cunha - Órgão Especial'),
('556', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 4ª Câmara'),
('169', 'Gabinete do Desembargador João Alberto Alves Machado - 10ª Câmara'),
('122', 'Gabinete do Desembargador João Alberto Alves Machado - SDC'),
('168', 'Gabinete do Desembargador José Otávio de Souza Ferreira - 2ª Câmara'),
('113', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - 2ª SDI'),
('109', 'Gabinete do Desembargador Samuel Hugo Lima - SDC'),
('498', 'Gabinete do Desembargador Samuel Hugo Lima - 4ª Câmara'),
('448', 'Gabinete do Desembargador Wilton Borba Canicoba - SDC'),
('49', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - 1ª SDI'),
('136', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - 6ª Câmara'),
('94', 'Gabinete da Desembargadora Antonia Regina Tancini Pestana - 2ª SDI'),
('137', 'Gabinete da Desembargadora Antonia Regina Tancini Pestana - 6ª Câmara'),
('57', 'Gabinete da Desembargadora Eleonora Bordini Coca - 2ª SDI'),
('140', 'Gabinete da Desembargadora Eleonora Bordini Coca - 4ª Câmara'),
('142', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - 5ª Câmara'),
('530', 'Gabinete do Desembargador Hélio Grasselli - 11ª Câmara'),
('150', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - 4ª Câmara'),
('153', 'Gabinete da Desembargadora Tereza Aparecida Asta Gemignani - 1ª Câmara'),
('154', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - 9ª Câmara'),
('271', 'Gabinete do Desembargador Renato Henry Sant''Anna  - Órgão Especial'),
('385', 'Gabinete da Vice-Presidência Judicial - Pleno - IUJ/ARG/IRDR'),
('523', 'Gabinete da Desembargadora Andrea Guelfi Cunha - 7ª Câmara'),
('403', 'Gabinete do Desembargador Jorge Luiz Costa - Órgão Especial'),
('542', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 1ª SDI'),
('517', 'Gabinete do Desembargador Marcos da Silva Porto - 7ª Câmara'),
('504', 'Gabinete da Desembargadora Erodite Ribeiro dos Santos - Órgão Especial'),
('214', 'Gabinete do Desembargador Carlos Augusto Escanfella - Tribunal Pleno'),
('215', 'Gabinete do Desembargador Claudinei Zapata Marques - Tribunal Pleno'),
('216', 'Gabinete do Desembargador Dagoberto Nishina de Azevedo - Tribunal Pleno'),
('160', 'Gabinete do Desembargador Eder Sivers - 11ª Câmara'),
('174', 'Gabinete da Desembargadora Antonia Sant''Ana - 7ª Câmara'),
('507', 'Gabinete da Desembargadora Mari Angela Pelegrini - 4ª Câmara'),
('334', 'Vaga Aposent. da Desembargadora Suzana Monreal Ramos Nogueira - 1ª Câmara'),
('543', 'Gabinete do Desembargador João Alberto Alves Machado - 9ª Câmara'),
('218', 'Gabinete do Desembargador Edmundo Fraga Lopes - Tribunal Pleno'),
('544', 'Gabinete do Desembargador Samuel Hugo Lima - 9ª Câmara'),
('235', 'Gabinete da Desembargadora Rita de Cássia Scagliusi do Carmo - Tribunal Pleno'),
('72', 'Gabinete da Desembargadora Antonia Sant''Ana - 1ª SDI'),
('223', 'Gabinete do Desembargador Marcos da Silva Porto - 10ª Câmara'),
('224', 'Gabinete do Desembargador José Pitas - 3ª Câmara'),
('179', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - 6ª Câmara'),
('180', 'Gabinete do Desembargador Samuel Hugo Lima - 5ª Câmara'),
('187', 'Gabinete da Desembargadora Ana Amarylis Vivacqua de Oliveira Gulla - Tribunal Pleno'),
('190', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - Órgão Especial'),
('301', 'Gabinete da Desembargadora Antonia Regina Tancini Pestana - 3ª Câmara'),
('450', 'Gabinete da Desembargadora Antonia Regina Tancini Pestana - Órgão Especial'),
('193', 'Gabinete da Desembargadora Eleonora Bordini Coca - Tribunal Pleno'),
('141', 'Gabinete da Desembargadora Erodite Ribeiro dos Santos - 8ª Câmara'),
('195', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - Tribunal Pleno'),
('196', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - Órgão Especial'),
('206', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - Tribunal Pleno'),
('207', 'Gabinete da Desembargadora Susana Graciela Santiso - Tribunal Pleno'),
('210', 'Gabinete da Desembargadora Tereza Aparecida Asta Gemignani - Órgão Especial'),
('211', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - Tribunal Pleno'),
('508', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - 3ª SDI'),
('513', 'Gabinete do Desembargador Hélio Grasselli - 1ª Câmara'),
('71', 'Gabinete da Desembargadora Keila Nogueira Silva - 1ª SDI'),
('172', 'Gabinete do Desembargador Luiz Antonio Lazarim - 1ª Câmara'),
('116', 'Gabinete do Desembargador Marcos da Silva Porto - SDC'),
('361', 'Gabinete do Desembargador Flavio Nunes Campos - Órgão Especial'),
('286', 'Gabinete do Desembargador Manuel Soares Ferreira Carradita - Órgão Especial'),
('69', 'Vaga Aposent. do Desembargador Luis Carlos Candido Martins Sotero da Silva - 1ª SDI'),
('390', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - 6ª Câmara'),
('273', 'Gabinete da Desembargadora Adriene Sidnei de Moura David- Órgão Especial'),
('558', 'Gabinete do Desembargador Gerson Lacerda Pistori - 7ª Câmara'),
('285', 'Gabinete do Desembargador Luis Roberto Nunes - Órgão Especial'),
('260', 'Gabinete do Desembargador Nildemar da Silva Ramos - Tribunal Pleno'),
('233', 'Gabinete do Desembargador Flavio Allegretti de Campos Cooper - Tribunal Pleno'),
('548', 'Gabinete do Desembargador Levi Rosa Tomé - 2ª SDI'),
('269', 'Gabinete do Desembargador Edmundo Fraga Lopes - Órgão Especial'),
('192', 'Gabinete da Desembargadora Elency Pereira Neves - Tribunal Pleno'),
('272', 'Gabinete do Desembargador Flavio Allegretti de Campos Cooper - Órgão Especial'),
('234', 'Gabinete do Desembargador Fábio Bueno de Aguiar - Tribunal Pleno'),
('248', 'Gabinete do Desembargador João Alberto Alves Machado - Tribunal Pleno'),
('279', 'Gabinete do Desembargador João Alberto Alves Machado - Órgão Especial'),
('277', 'Gabinete do Desembargador José Otávio de Souza Ferreira - Órgão Especial'),
('257', 'Gabinete da Desembargadora Antonia Sant''Ana - Tribunal Pleno'),
('553', 'Vaga Aposent. do Desembargador Ricardo Regis Laraia - 9ª Câmara'),
('258', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - Tribunal Pleno'),
('263', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - Tribunal Pleno'),
('264', 'Gabinete do Desembargador Samuel Hugo Lima - Tribunal Pleno'),
('289', 'Gabinete do Desembargador Samuel Hugo Lima - Órgão Especial'),
('402', 'Gabinete do Desembargador Wilton Borba Canicoba - Órgão Especial'),
('55', 'Gabinete da Desembargadora Erodite Ribeiro dos Santos - 1ª SDI'),
('194', 'Gabinete da Desembargadora Erodite Ribeiro dos Santos - Tribunal Pleno'),
('396', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - 3ª SDI'),
('209', 'Gabinete da Desembargadora Tereza Aparecida Asta Gemignani - Tribunal Pleno'),
('392', 'Gabinete do Desembargador Luis Henrique Rafael - 11ª Câmara'),
('349', 'Gabinete do Desembargador Luis Henrique Rafael - 1ª Câmara'),
('406', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 1ª Câmara'),
('247', 'Gabinete do Desembargador Orlando Amâncio Taveira - Tribunal Pleno'),
('278', 'Gabinete do Desembargador José Pitas - Órgão Especial'),
('266', 'Gabinete do Desembargador Thomas Malm - Tribunal Pleno'),
('284', 'Gabinete do Desembargador Luiz José Dezena da Silva - Órgão Especial'),
('398', 'Vaga Aposent. do Desembargador Manuel Soares Ferreira Carradita - 2ª SDI'),
('353', 'Gabinete do Juiz do Trabalho Convocado - 1ª Câmara'),
('293', 'Gabinete da Corregedoria Regional'),
('110', 'Gabinete do Desembargador Levi Rosa Tomé - 3ª SDI'),
('173', 'Vaga do Desembargador Luiz José Dezena da Silva - 4ª Câmara'),
('374', 'Gabinete da Desembargadora Antonia Sant''Ana - 8ª Câmara'),
('528', 'Vaga Aposent. da Desembargadora Rita de Cássia Scagliusi do Carmo - 4ª Câmara'),
('225', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 8ª Câmara'),
('545', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - 5ª Câmara'),
('188', 'Gabinete da Desembargadora Ana Maria de Vasconcellos - Tribunal Pleno'),
('268', 'Gabinete do Desembargador Claudinei Zapata Marques - Órgão Especial'),
('511', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 4ª Câmara'),
('123', 'Gabinete do Desembargador Hélio Grasselli - SDC'),
('363', 'Gabinete da Desembargadora Helena Rosa Mônaco da Silva Lins Coelho - Órgão Especial'),
('100', 'Gabinete da Desembargadora Tereza Aparecida Asta Gemignani - SDC'),
('331', 'Gabinete do Desembargador Edison dos Santos Pelegrini - 3ª SDI'),
('337', 'Gabinete do Desembargador Edison dos Santos Pelegrini - Tribunal Pleno'),
('397', 'Gabinete do Desembargador Gerson Lacerda Pistori - 3ª SDI'),
('311', 'Gabinete do Desembargador João Batista Martins César - 3ª SDI'),
('280', 'Gabinete do Desembargador Lorival Ferreira dos Santos - Órgão Especial'),
('320', 'Gabinete do Desembargador Luiz Felipe Paim da Luz Bruno Lobo - Tribunal Pleno'),
('408', 'Gabinete do Desembargador Roberto Nóbrega de Almeida Filho - Órgão Especial'),
('47', 'Gabinete da Desembargadora Ana Amarylis Vivacqua de Oliveira Gulla - 1ª SDI'),
('131', 'Gabinete da Desembargadora Ana Amarylis Vivacqua de Oliveira Gulla - 3ª Câmara'),
('368', 'Gabinete da Desembargadora Ana Amarylis Vivacqua de Oliveira Gulla - Órgão Especial'),
('312', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - 3ª SDI'),
('559', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 9ª Câmara'),
('484', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - 1ª Câmara'),
('371', 'Gabinete do Desembargador José Carlos Ábile - 3ª Câmara'),
('380', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - 3ª SDI'),
('405', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - 8ª Câmara'),
('399', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - Tribunal Pleno'),
('400', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - Órgão Especial'),
('129', 'Vaga Aposent. do Desembargador José Pedro de Camargo Rodrigues de Souza - 3ª SDI'),
('445', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 7ª Câmara'),
('217', 'Gabinete do Desembargador Eder Sivers - Tribunal Pleno'),
('332', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 2ª SDI'),
('255', 'Gabinete do Desembargador Renato Henry Sant''Anna - Tribunal Pleno'),
('143', 'Gabinete do Desembargador Hélio Grasselli - 2ª Câmara'),
('175', 'Gabinete do Desembargador Manoel Carlos Toledo Filho - 4ª Câmara'),
('199', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - Tribunal Pleno'),
('497', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - 8ª Câmara'),
('352', 'Gabinete do Desembargador Orlando Amâncio Taveira - 9ª Câmara'),
('197', 'Gabinete do Desembargador Hélio Grasselli - Tribunal Pleno'),
('541', 'Gabinete do Desembargador Marcelo Garcia Nunes - 3ª Câmara'),
('477', 'Gabinete da Vice-Presidência Judicial - Análise de Recurso'),
('470', 'Gabinete do Juiz do Trabalho Convocado - 3ª Câmara'),
('372', 'Gabinete do Juiz do Trabalho Convocado - 6ª Câmara'),
('181', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 8ª Câmara'),
('219', 'Gabinete da Desembargadora Mari Angela Pelegrini - 2ª Câmara'),
('463', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 2ª SDI'),
('64', 'Gabinete do Desembargador João Batista da Silva - 3ª SDI'),
('166', 'Gabinete do Desembargador Helcio Dantas Lobo Junior - 3ª Câmara'),
('275', 'Gabinete do Desembargador Helcio Dantas Lobo Junior - Órgão Especial'),
('307', 'Gabinete do Desembargador João Batista Martins César - SDC'),
('495', 'Gabinete do Desembargador Orlando Amâncio Taveira - 1ª Câmara'),
('494', 'Gabinete do Desembargador Hélio Grasselli - 6ª Câmara'),
('338', 'Gabinete do Desembargador Marcelo Garcia Nunes - Tribunal Pleno'),
('506', 'Gabinete do Desembargador Marcelo Garcia Nunes - 11ª Câmara'),
('170', 'Gabinete da Desembargadora Andrea Guelfi Cunha - 5ª Câmara'),
('509', 'Gabinete da Desembargadora Mari Angela Pelegrini - 2ª SDI'),
('93', 'Gabinete da Desembargadora Mari Angela Pelegrini - 3ª SDI'),
('227', 'Gabinete da Desembargadora Mari Angela Pelegrini - Tribunal Pleno'),
('149', 'Gabinete da Desembargadora Olga Aida Joaquim Gomieri - 11ª Câmara'),
('444', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 1ª Câmara'),
('451', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - Tribunal Pleno'),
('456', 'Gabinete da Desembargadora Maria Inês Correa de Cerqueira César Targa - Órgão Especial'),
('532', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 7ª Câmara'),
('496', 'Gabinete do Desembargador Hélio Grasselli - Órgão Especial'),
('526', 'Gabinete do Desembargador Marcos da Silva Porto - 5ª Câmara'),
('292', 'Gabinete da Vice-Presidência Administrativa'),
('261', 'Gabinete do Desembargador Renato Buratto - Tribunal Pleno'),
('288', 'Gabinete do Desembargador Renato Buratto - Órgão Especial'),
('356', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - Tribunal Pleno'),
('468', 'Credenciamento de Leiloeiros e Corretores'),
('324', 'Gabinete do Desembargador Luiz Felipe Paim da Luz Bruno Lobo - 11ª Câmara'),
('302', 'Vaga Aposent. do Desembargador José Pedro de Camargo Rodrigues de Souza - 6ª Câmara'),
('322', 'Gabinete do Desembargador Paulo Augusto Ferreira - 1ª Câmara'),
('186', 'Vaga Aposent. do Desembargador Laurival Ribeiro da Silva Filho - 1ª Câmara'),
('80', 'Vaga Aposent. do Desembargador Laurival Ribeiro da Silva Filho - 1ª SDI'),
('132', 'Vaga Aposent. do Desembargador Laurival Ribeiro da Silva Filho - SDC'),
('317', 'Vaga Aposent. da Desembargadora Elency Pereira Neves - 1ª SDI'),
('296', 'Gabinete da Desembargadora Elency Pereira Neves - 1ª SDI'),
('471', 'Gabinete do Juiz do Trabalho Convocado - 7ª Câmara'),
('321', 'Gabinete do Desembargador Luiz Felipe Paim da Luz Bruno Lobo - 1ª Câmara'),
('330', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - 1ª SDI'),
('323', 'Vaga Aposent. do Desembargador Laurival Ribeiro da Silva Filho - 11ª Câmara'),
('510', 'Gabinete do Desembargador Orlando Amâncio Taveira - SDC'),
('455', 'Gabinete da Desembargadora Thelma Helena Monteiro de Toledo Vieira - Órgão Especial'),
('103', 'Gabinete do Desembargador Hélio Grasselli - 2ª SDI'),
('325', 'Gabinete do Desembargador Renato Henry Sant''Anna - 9ª Câmara'),
('335', 'Gabinete do Desembargador Marcelo Garcia Nunes - 9ª Câmara'),
('348', 'Vaga Aposent. do Desembargador Ricardo Regis Laraia - 6ª Câmara'),
('474', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 3ª SDI'),
('459', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 4ª Câmara'),
('226', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 6ª Câmara'),
('111', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - SDC'),
('500', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim  - 3ª Câmara'),
('492', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 2ª Câmara'),
('462', 'Gabinete do Desembargador João Batista da Silva - 2ª SDI'),
('319', 'Gabinete do Desembargador Luiz Felipe Paim da Luz Bruno Lobo - 3ª SDI'),
('457', 'Gabinete da Desembargadora Luciane Storer - Órgão Especial'),
('134', 'Gabinete do Desembargador Marcelo Garcia Nunes - 3ª SDI'),
('487', 'Gabinete do Desembargador Marcelo Garcia Nunes - 8ª Câmara'),
('512', 'Gabinete da Desembargadora Mari Angela Pelegrini - 7ª Câmara'),
('452', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 6ª Câmara'),
('351', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 1ª SDI'),
('299', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 3ª SDI'),
('535', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 10ª Câmara'),
('533', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 8ª Câmara'),
('562', 'Gabinete do Desembargador Representante da 3ª Câmara na SUJ'),
('571', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 11ª Câmara'),
('333', 'Gabinete do Desembargador Eder Sivers - SDC'),
('237', 'Gabinete do Desembargador Fabio Grasselli - Tribunal Pleno'),
('182', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - 10ª Câmara'),
('386', 'Vaga Aposent. do Desembargador Ricardo Regis Laraia  Ricardo Regis Laraia - 10ª Câmara'),
('389', 'Gabinete do Juiz do Trabalho Convocado - 10ª Câmara'),
('393', 'Gabinete do Desembargador Luis Henrique Rafael - SDC'),
('112', 'Vaga Aposent. da Desembargadora Rita de Cássia Scagliusi do Carmo - SDC'),
('185', 'Vaga Aposent. do Desembargador José Antonio Pancotti - 1ª Câmara'),
('198', 'Gabinete da Desembargadora Maria Cecília Fernandes Álvares Leite - Tribunal Pleno'),
('563', 'Gabinete do Desembargador Representante da 4ª Câmara na SUJ'),
('453', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - 1ª Câmara'),
('382', 'Gabinete do Juiz do Trabalho Convocado - 11ª Câmara'),
('239', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - Tribunal Pleno'),
('159', 'Gabinete do Desembargador Dagoberto Nishina de Azevedo - 4ª Câmara'),
('274', 'Gabinete do Desembargador Gerson Lacerda Pistori - Órgão Especial'),
('370', 'Gabinete do Desembargador Wilton Borba Canicoba - 2ª Câmara'),
('381', 'Gabinete do Desembargador Wilton Borba Canicoba - 2ª SDI'),
('329', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - 5ª Câmara'),
('189', 'Gabinete da Desembargadora Ana Paula Pellegrina Lockmann - Tribunal Pleno'),
('191', 'Gabinete da Desembargadora Antonia Regina Tancini Pestana - Tribunal Pleno'),
('61', 'Gabinete da Desembargadora Gisela Rodrigues Magalhães de Araújo e Moraes - 1ª SDI'),
('376', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 7ª Câmara'),
('305', 'Vaga Aposent. do Desembargador José Pedro de Camargo Rodrigues de Souza - 1ª Câmara'),
('183', 'Vaga Aposent. do Desembargador José Pedro de Camargo Rodrigues de Souza - 3ª Câmara'),
('446', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 2ª SDI'),
('387', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - 6ª Câmara'),
('394', 'Gabinete do Desembargador Fábio Bueno de Aguiar - 1ª Câmara'),
('473', 'Gabinete do Desembargador Orlando Amâncio Taveira - 8ª Câmara'),
('176', 'Gabinete da Desembargadora Keila Nogueira Silva - 7ª Câmara'),
('259', 'Gabinete da Desembargadora Keila Nogueira Silva - Tribunal Pleno'),
('447', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - SDC'),
('395', 'Gabinete do Desembargador Hélio Grasselli - 3ª SDI'),
('281', 'Gabinete do Desembargador Luiz Antonio Lazarim - Órgão Especial'),
('205', 'Gabinete da Desembargadora Olga Aida Joaquim Gomieri - Órgão Especial'),
('343', 'Vaga Aposent. do Desembargador Luis Carlos Candido Martins Sotero da Silva - 6ª Câmara'),
('502', 'Gabinete da Desembargadora Larissa Carotta Martins da Silva Scarabelim - Órgão Especial'),
('304', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 6ª Câmara'),
('121', 'Vaga Aposent. do Desembargador Ricardo Regis Laraia - 2ª SDI'),
('564', 'Gabinete do Desembargador Representante da 5ª Câmara na SUJ'),
('345', 'Gabinete de Desembargador Suplente no Órgão Especial 4'),
('460', 'Gabinete do Desembargador João Batista da Silva - 1ª Câmara'),
('467', 'Gabinete do Desembargador João Batista da Silva - 6ª Câmara'),
('461', 'Gabinete do Desembargador João Batista da Silva - SDC'),
('488', 'Gabinete do Desembargador João Batista da Silva - 11ª Câmara'),
('155', 'Gabinete do Desembargador Antonio Francisco Montanagna - 10ª Câmara'),
('89', 'Gabinete do Desembargador Antonio Francisco Montanagna - SDC'),
('212', 'Gabinete do Desembargador Antonio Francisco Montanagna - Tribunal Pleno'),
('373', 'Gabinete do Desembargador Carlos Alberto Bosco - 1ª SDI'),
('114', 'Gabinete do Desembargador Carlos Alberto Bosco - 2ª SDI'),
('133', 'Gabinete do Desembargador Carlos Alberto Bosco - 3ª SDI'),
('156', 'Gabinete do Desembargador Carlos Alberto Bosco - 7ª Câmara'),
('213', 'Gabinete do Desembargador Carlos Alberto Bosco - Tribunal Pleno'),
('336', 'Gabinete do Desembargador Marcelo Magalhães Rufino - Tribunal Pleno'),
('505', 'Gabinete do Desembargador Marcelo Magalhães Rufino - 1ª Câmara'),
('565', 'Gabinete do Desembargador Representante da 6ª Câmara na SUJ'),
('256', 'Gabinete do Desembargador João Batista da Silva - Tribunal Pleno'),
('96', 'Gabinete da Desembargadora Andrea Guelfi Cunha - SDC'),
('118', 'Gabinete da Desembargadora Adriene Sidnei de Moura David - 3ª SDI'),
('486', 'Gabinete do Desembargador João Batista da Silva - 8ª Câmara'),
('339', 'Gabinete do Desembargador Antonio Francisco Montanagna - 11ª Câmara'),
('566', 'Gabinete do Desembargador Representante da 7ª Câmara na SUJ'),
('158', 'Gabinete do Desembargador Claudinei Zapata Marques - 8ª Câmara'),
('567', 'Gabinete do Desembargador Representante da 8ª Câmara na SUJ'),
('568', 'Gabinete do Desembargador Representante da 9ª Câmara na SUJ'),
('569', 'Gabinete do Desembargador Representante da 10ª Câmara na SUJ'),
('570', 'Gabinete do Desembargador Representante da 11ª Câmara na SUJ'),
('200', 'Gabinete do Desembargador Levi Rosa Tomé - Tribunal Pleno'),
('157', 'Gabinete da Desembargadora Ana Cláudia Torres Vianna - 7ª Câmara'),
('144', 'Vaga Aposent. da Desembargadora Maria Cecília Fernandes Álvares Leite - 11ª Câmara'),
('108', 'Gabinete do Desembargador José Otávio de Souza Ferreira - 2ª SDI'),
('106', 'Gabinete do Desembargador Paulo Augusto Ferreira - 3ª SDI'),
('245', 'Gabinete do Desembargador José Otávio de Souza Ferreira - Tribunal Pleno'),
('91', 'Vaga Aposent. do Desembargador Carlos Augusto Escanfella - 2ª SDI'),
('135', 'Gabinete do Desembargador Carlos Eduardo Oliveira Dias - 5ª Câmara'),
('73', 'Vaga Aposent. do Desembargador José Antonio Pancotti - 1ª SDI'),
('85', 'Vaga Aposent. da Desembargadora Ana Maria de Vasconcellos - SDC'),
('344', 'Vaga Aposent. da Desembargadora Maria Cecília Fernandes Álvares Leite - 10ª Câmara'),
('152', 'Vaga Aposent. da Desembargadora Suzana Monreal Ramos Nogueira - 9ª Câmara'),
('203', 'Gabinete do Desembargador Paulo Augusto Ferreira - Tribunal Pleno'),
('63', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - 3ª SDI'),
('276', 'Gabinete do Desembargador Henrique Damiano - Órgão Especial'),
('366', 'Gabinete da Desembargadora Rita de Cássia Penkal Bernardino de Souza - Órgão Especial'),
('105', 'Gabinete da Desembargadora Susana Graciela Santiso - 3ª SDI'),
('364', 'Gabinete da Desembargadora Susana Graciela Santiso - Órgão Especial'),
('148', 'Gabinete do Desembargador José Carlos Ábile - 2ª Câmara'),
('102', 'Gabinete do Desembargador José Carlos Ábile - 2ª SDI'),
('99', 'Gabinete da Desembargadora Rosemeire Uehara Tanaka - SDC'),
('404', 'Gabinete do Desembargador Renan Ravel Rodrigues Fagundes - 3ª SDI'),
('449', 'Gabinete do Desembargador Fábio Bueno de Aguiar - 2ª SDI'),
('161', 'Gabinete do Desembargador Edmundo Fraga Lopes - 3ª Câmara'),
('270', 'Gabinete do Desembargador Eduardo Benedito de Oliveira Zanella - Órgão Especial'),
('95', 'Gabinete do Desembargador Fabio Grasselli - 3ª SDI'),
('409', 'Gabinete do Desembargador Helcio Dantas Lobo Junior - 3ª SDI'),
('240', 'Gabinete do Desembargador Helcio Dantas Lobo Junior - Tribunal Pleno'),
('391', 'Gabinete do Desembargador José Pedro de Camargo Rodrigues de Souza - 1ª Câmara'),
('117', 'Gabinete da Desembargadora Maria da Graça Bonança Barbosa - SDC')
ON CONFLICT (codigo) DO NOTHING;